first ver - header
MichalRzeszot/goit-group-project-bookshelf pull request #6
Opened 2023-12-28 21:16 UTC by inezkaj

2023-12-29 17:27 UTC, MichalRzeszot requested changes

2023-12-29 17:27 UTC, MichalRzeszot commented on src/partials/header.html
> +      <img width="40" height="20" src="./images/Switcher.svg" />
Switcher nie jest ikoną, powinien się zmieniać po kliknięciu w niego tak jak w figmie.

2023-12-30 11:32 UTC, WKotlinski approved these changes
Wszystko wydaje się w porządku. Nie sprawdzam wartości, bo wierze że się zgadzają z figmą

2023-12-30 12:25 UTC, MichalRzeszot approved these changes
Wszystko ok ;)

2023-12-30 12:29 UTC, merged